kumuluzee:
  server:
    base-url: http://localhost:8080
  datasources:
    - jndi-name: jdbc/WorkshopMarketDS
      connection-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      max-pool-size: 20